services:
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: "renato3x"
      POSTGRES_PASSWORD: "1069"
      POSTGRES_DB: "webhook_gateway_app"
    ports:
      - "5432:5432"
    volumes:
      - database_vm:/var/lib/postgresql
volumes:
  database_vm: